language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BsLNHELWQ2+JnZ8yb3XHpzS5Mp2K1AJTlEXLEhR9gGgckwVOiBFBDj354je5md/9c4QzmCQQy4sianwqVGfsjU3O8/3tGBwVCPwuLauoycIU5FkeBu+JXujfNT12gFOAC8/7oAwTEnBzMeagrhFjB8Eyo1Xq85ubHVkc1ocU0OHa5yQUhVZaEB1DBhU8Wmt93ODYkpKfjBopZ6z8maEWZhIMs59Q8AIFnkamIvNKXMqBPEhULUuOMgsH3AeRJZn2SBffZSXPx7y5jLMqCMoMLvUL8vDdtq/B+EOwFV41GoL6WL1mrwhfJ5iddLq/2mnboq7n6rYEA/udr4mKKdHSow3DC9rTm8VCWGScIXEXlpgGyCgT3JtR7O89CjG+BCj07fKQK92hywsN13jRMVzEeShDBo+xtY1Ox+VkCE4NLNNZX7ZwSJcPNyvW3bOY3u6jUzxtMyEmfuy5e5fZgEpqOyelnZFRkaWQZAvpf1SNSj4dWikC2aboIvSD0R6qVbKRo13t6q4DNY5c8LNcgOTSay9q8SlkXoQLeUlQt4H1Dy4DE7UfZk0/zh3iiVltyuV9Qgn7xkdxDdrkCB3p6Xu3xVNR1cPNPrKEhhmEZ9MKNy+Vb1ERY6ry+9QEIoZEdrSAjhaWFAIukAs/EF1eqN4ylFL5GgvJ9QAFE76hRXNvaUs="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_install:
  - pip install --user codecov
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "dminarik/nomad-client"
      description: "<Your project description here>"
    notification_email: darkominarik@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compile"
    branch_pattern: master
