language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_install:
  - pip install --user codecov
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SoSCiTJTeac8qBPF7Qg9jq9XyGwPvRAFJQi8Y7NUE9jiNV+TIuQ9C5LfNKjPKs08eGiTm0bneu9YumjN8EdW3OJ8kqnqQZd3q7mA38JBGWyg1QUu3817+SF51dCnoYaaejQigZ3P3n4QZJleoT5tc7Qc3Gf3zOngAlGV2gIx5YAF3CqWRDpeslGhEsypZDfvO1Vkq4rNcWnx2M1HfyTKI1wx8TTksTkglCm9rQH4L1XZRuSwlA8YGDX1AV7MgHnil8GftDGwUHJWN7VlNGflHcp+b4a9qBZKniFZ4AfTQHZ8o2Ic7YbqTpN9qDtXXLVD4xUNzqg3rmHpnR2l40d2+9mC6I5zMrR+GjhODkbR4R/953+5caKc52n8s3+pTlmLHm8AJIRkBE0WgRfB3AnJ4OWsY3rfB7XYndrnbkxd5wlHtyL/iI/UFZFAZK+a3UClh6sxl8dg83usJQNHDriG7FyJWfxWMMkxm233etjk+073ahGDAy1yzDkrP/nMi1/JcgX4uhuc0FrPU5npiKsAAz6EdzDi8DZHIMfhCFePskpEf1ajSK50sbYUyq+fN3klP+QCdKvHXNLzhKxf6emWY0JGKwW7VFj9G+Ql+KsQzwa1UTtEDI5K8kyW2NZo6WczMZWeky57C+CAxFG0LxFF8W/WlX7jL6cJyMup3rEqQLc="
   
addons:
  coverity_scan:
    project:
      name: "dminarik/nomad-client"
      description: "<Your project description here>"
    notification_email: darkominarik@gmail.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command:   "<Your build command here>"
    branch_pattern: coverity_scan
